### ISSUE TITLE
убери фашистский флаг

### ISSUE THREAD

**Issue by Gemorroj** [DarkRiDDeR/dlang.ru#4]
https://github.com/DarkRiDDeR/dlang.ru/commit/bb9c10302bd8d27fdf888d7bc287e0827e4f9bdd
не будь мразью, убери фашистское скотство

**Comment by DarkRiDDeR** [comment]
Здрасти. Зачем выражаться так грубо? И причём здесь фашизм? 
Вообще политические вопросы, конечно, к тематики подобных сайтов не относится. Но так захотел в своё время предыдущий владелец сайта. В данный момент мне идёт переход всех прав по управлению. Как это процесс закончится, то обещаю политический тематики не вставлять. А пока побудет так.
