### ISSUE TITLE
Обратная связь

### ISSUE THREAD

**Issue by 0xdecade** [DarkRiDDeR/dlang.ru#9]
С кем можно связаться по поводу разбана на telegram канале dlang.ru?
Нажал Join и не заметил что там антиспам ждал кнопку целых 30 секунд, после чего тот меня естетвенно кикнул, а на сайте никаких контактов нет.

**Comment by DarkRiDDeR** [comment]
Привет. Давай напишу в группу. Логин какой в телеге?

**Comment by 0xdecade** [comment]
@DarkRiDDeR xdecade

**Comment by DarkRiDDeR** [comment]
@0xdecade я у тебя посмотрел в акке твой логин ) Уже написал, должны разбанить, проверь

**Comment by 0xdecade** [comment]
Проверил, но до сих пор получаю "У Вас нет доступа к этому чату, так как Вас заблокировал его администратор"

**Comment by DarkRiDDeR** [comment]
@0xdecade напиши @darkhole1 в телеге
